title: MadeKumis
description: Aplikasi berita Bali terkini, baca berita jadi cepat dan mudah.
show_downloads: false
theme: jekyll-theme-cayman
gatrabali:
  android_download_url: https://play.google.com/store/apps/details?id=com.gatrabali.android